// TableInitialValues
// this file contains the initial data for the tables in the app
// this file is used to generate forms

export const TableInitialValues = {
  bitacoraLimpiezaRecibos: {
    areaArmado: 0,
    areaRecibo: 0,
    patio: 0,
    rampas: 0,
    cuartosFrios: 0,
    congelador: 0,
    transporte: 0,
    observaciones: "",
  },

  bitacoraLimpiezaEmpaques: {
    pisos: 0,
    mesas: 0,
    selladores: 0,
    basculas: 0,
    rampas: 0,
    estantes: 0,
    bandejas: 0,
    patines: 0,
    observaciones: "",
  },

  bitacoraLimpiezaCribasFV: {
    pisos: 0,
    mesas: 0,
    patio: 0,
    basculas: 0,
    rampas: 0,
    rejillas: 0,
    patines: 0,
    observaciones: "",
  },
  bitacoraLimpiezaAlmacenes: {
    pisos: 0,
    pasillos: 0,
    extintores: 0,
    cuartosFrios: 0,
    puertas: 0,
    muros: 0,
    racks: 0,
    cortinas: 0,
    coladeras: 0,
    rejillas: 0,
    montacargas: 0,
    patines: 0,
    observaciones: "",
  },
  bitacoraLimpiezaEntregas: {
    pisos: 0,
    cuartosFrios: 0,
    basculas: 0,
    racks: 0,
    cortinas: 0,
    rampas: 0,
    patines: 0,
    observaciones: "",
  },
  bitacoraLimpiezaAlimentoCompartidos: {
    pisos: 0,
    cuartosFrios: 0,
    refrigeradores: 0,
    congeladores: 0,
    racks: 0,
    cortinas: 0,
    patines: 0,
    basculas: 0,
    observaciones: "",
  },
  bitacoraTemperaturas: {
    cuartoFrio1: 0,
    cuartoFrio2: 0,
    camaraConservacionB: 0,
    camaraConservacionA: 0,
    observaciones: "",
  },
  bitacoraIncidentes: {
    nombre: "",
    descripcion: "",
    imagen: "",
  },
  bitacoraExtintores: {
    capacidad: 0,
    manometro: 0,
    estadoFisico: 0,
    mangueras: 0,
    seguro: 0,
    etiquetas: 0,
    holograma: 0,
    ultimaRevision: 0,
    proximaRecarga: 0,
    observaciones: 0,
  },
};
