// TableInitialValues
// this file contains the initial data for the tables in the app
// this file is used to generate forms

export const TableInitialValues = {
  bitacoraLimpiezaRecibos: {
    areaArmado: false,
    areaRecibo: false,
    patio: false,
    rampas: false,
    cuartosFrios: false,
    congelador: false,
    transporte: false,
    observaciones: "",
  },

  bitacoraLimpiezaEmpaques: {
    pisos: false,
    mesas: false,
    selladores: false,
    basculas: false,
    rampas: false,
    estantes: false,
    bandejas: false,
    patines: false,
    observaciones: "",
  },

  bitacoraLimpiezaCribasFV: {
    pisos: false,
    mesas: false,
    patio: false,
    basculas: false,
    rampas: false,
    rejillas: false,
    patines: false,
    observaciones: "",
  },
  bitacoraLimpiezaAlmacenes: {
    pisos: false,
    pasillos: false,
    extintores: false,
    cuartosFrios: false,
    puertas: false,
    muros: false,
    racks: false,
    cortinas: false,
    coladeras: false,
    rejillas: false,
    montacargas: false,
    patines: false,
    observaciones: "",
  },
  bitacoraLimpiezaEntregas: {
    pisos: false,
    cuartosFrios: false,
    basculas: false,
    racks: false,
    cortinas: false,
    rampas: false,
    patines: false,
    observaciones: "",
  },
  bitacoraLimpiezaAlimentoCompartidos: {
    pisos: false,
    cuartosFrios: false,
    refrigeradores: false,
    congeladores: false,
    racks: false,
    cortinas: false,
    patines: false,
    basculas: false,
    observaciones: "",
  },
  bitacoraTemperaturas: {
    cuartoFrio1: 0,
    cuartoFrio2: 0,
    camaraConservacionB: 0,
    camaraConservacionC: 0,
    observaciones: "",
  },
  bitacoraIncidentes: {
    nombre: "",
    descripcion: "",
    imagen: "",
  },
  bitacoraExtintores: {
    capacidad: false,
    manometro: false,
    estadoFisico: false,
    mangueras: false,
    seguro: false,
    etiquetas: false,
    holograma: false,
    ultimaRevision: 0,
    proximaRecarga: 0,
    observaciones: 0,
  },
};
